app:
  title: "Databricks Chat App"
  catalog: ${env:APP_CATALOG, "shared"}
  schema: ${env:APP_SCHEMA, "app"}
  volume: ${env:APP_VOLUME, "user_files"}
  allowed_model_ids: ["sonnet-4"]
  features:
    enable_rag: false
    enable_sql_tool: false
    enable_budgets: true
