# .streamlit/config.toml
# Streamlit Configuration for Databricks AI Chat Assistant
# Place this file in a .streamlit folder in your project root

[server]
# Server configuration
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

# File upload configuration
fileWatcherType = "auto"

[browser]
# Browser configuration
gatherUsageStats = false
showErrorDetails = true

[theme]
# Modern dark theme inspired by Databricks branding
base = "dark"
primaryColor = "#FF6B35"        # Vibrant orange-red for interactive elements
backgroundColor = "#0D1117"     # Deep dark blue-gray background
secondaryBackgroundColor = "#1C2128"  # Slightly lighter for sidebar and widgets
textColor = "#F0F6FC"          # Light blue-white text for excellent contrast
font = "sans serif"            # Clean, modern font

[client]
# Client configuration
caching = true
displayEnabled = true
toolbarMode = "auto"

[ui]
# UI configuration
hideTopBar = false
hideSidebarNav = false

# Development settings (disable in production)
[development]
# Set to false in production
showErrorDetails = true

# Logger configuration
[logger]
level = "INFO"
messageFormat = "%(asctime)s %(message)s"