[theme]
# Primary accent - Beautiful gradient blue
primaryColor = "#5B8DEE"

# Main background - Deep space blue
backgroundColor = "#0F1419"

# Secondary background - Midnight blue
secondaryBackgroundColor = "#1A2332"

# Text - Soft white for excellent readability
textColor = "#E8EAED"

# Font - Clean and modern
font = "sans serif"